class city:
    def __init__(self):
        self.listCity = [
        "Rio de Janeiro",	
	"São Gonçalo",	
	"Duque de Caxias",	
	"Nova Iguaçu",	
	"Niterói",	
	"Belford Roxo",	
	"Campos dos Goytacazes",	
	"São João de Meriti",	
	"Petrópolis",	
	"Volta Redonda",	
	"Macaé",	
    	"Magé",	
	"Itaboraí",	
	"Cabo Frio",	
	"Angra dos Reis",	 
	"Nova Friburgo",	 
	"Barra Mansa",	 
	"Teresópolis",	 
	"Mesquita",	 
	"Maricá",	 
	"Nilópolis",	 
	"Rio das Ostras",	 
	"Queimados",	 
	"Itaguaí",	 
	"Araruama",	 
	"Resende",	 
	"São Pedro da Aldeia",	 
	"Japeri",	 
	"Itaperuna",	 
	"Barra do Piraí",	 
	"Seropédica",	 
	"Saquarema",	 
	"Três Rios",	 
	"Valença",
	"Guapimirim",	 
	"Rio Bonito",	 
	"Cachoeiras de Macacu",	 
	"Paracambi",	 
	"Mangaratiba",	 
	"Casimiro de Abreu",	 
	"Paraíba do Sul",	 
	"Paraty",	 
	"Santo Antônio de Pádua",	 
	"São Francisco de Itabapoana",	 
	"São Fidélis",	 
	"Bom Jesus do Itabapoana",	 
	"Vassouras",	 
	"São João da Barra",	 
	"Tanguá",	 
	"Armação dos Búzios",	 
	"Itatiaia",	 
	"Arraial do Cabo", 
	"Piraí",	 
	"Iguaba Grande",	 
	"Paty do Alferes",	 
	"Bom Jardim",
	"Miracema",
	"Miguel Pereira",
	"Pinheiral",
	"Quissamã",
	"Conceição de Macabu",	 
	"Itaocara",	 
	"Cordeiro",	 
	"São José do Vale do Rio Preto",	 
	"Silva Jardim",	 
	"Cantagalo",	 
	"Porto Real",	 
	"Carmo",	 
	"Porciúncula",	 
	"Mendes",	 
	"Rio Claro",	 
	"Sapucaia",	 
	"Carapebus",	 
	"Sumidouro",	 
	"Cambuci",	 
	"Natividade",	 
	"Italva", 
	"Quatis",	 
	"Engenheiro Paulo de Frontin",	 
	"Cardoso Moreira	", 
	"Areal",	 
	"Aperibé",	 
	"Duas Barras",	 
	"Varre-Sai",	 
	"Trajano de Moraes",	 
	"Santa Maria Madalena",	 
	"São Sebastião do Alto",	 
	"Rio das Flores",	 
	"Comendador Levy Gasparianv", 
	"Laje do Muriaé",	 
	"São José de Ubá", 
	"Macuco"
        ]
